@host = http://localhost:8080

### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Login admina
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "Firkowski",
  "rawPassword": "ZAQ!2wsx"
}

> {%
    client.global.set(
        "accessToken",
        response.body.accessToken
    )

    client.global.set(
        "refreshToken",
        response.body.refreshToken
    )
%}

### Refresh access tokena
POST {{host}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set(
        "accessToken",
        response.body.accessToken
    )
 %}


### Categories get
GET {{host}}/admin/categories
Authorization: Bearer {{accessToken}}
### Categories post

POST {{host}}/admin/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
   "name": "LO1"
}

### Categories delete

DELETE {{host}}/admin/categories/c0b7568e-ff1f-41fe-8082-cb3e41cba446
Authorization: Bearer {{accessToken}}


### Categories update
PUT {{host}}/admin/categories/6ff9b79b-c119-4374-b259-fc1dd289d3e3
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "xddd"
}

