@host = http://localhost:8080

### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Login admina
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "Firkowski",
  "rawPassword": "ZAQ!2wsx"
}

> {%
    client.global.set(
        "accessToken",
        response.body.accessToken
    )

    client.global.set(
        "refreshToken",
        response.body.refreshToken
    )
%}

### Refresh access tokena
POST {{host}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

